portal/urls.py
from django.conf.urls import url
from . import views

app_name = 'portal'

urlpatterns = [
    # /portal/
    url(r'^$', views.index, name='index'),

    # /portal/create
    url(r'^create/$', views.create, name='create'),

    # /portal/sendotp
    #url(r'^bulk/$', views.bulk, name='bulk'),

    # # /portal/sendotp
    # url(r'^sendotp/$', views.sendotp, name='sendotp'),

    # /portal/verifyotp
    url(r'^verifyotp/$', views.verify_otp, name='verifyotp'),

    # /portal/activate/34/44eee003-b342-4904-af4f-ef1b6d41e6ee
    url(r'^activate/(?P<uid>[0-9]+)/(?P<token>[^/]+)/$', views.activate, name='activate'),
]

portal/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import RegexValidator

fname = RegexValidator(r'^[a-zA-Z \-\']+$', 'First name can contain letters (A-z) and dash (-) only')
lname = RegexValidator(r'^[a-zA-Z \-\']+$', 'Family name can contain letters (A-z) and dash (-) only')

class User(models.Model):
    fname = models.CharField(max_length=100, validators=[fname])
    lname = models.CharField(max_length=100, validators=[lname])
    email = models.EmailField(max_length=100)
    phone = PhoneNumberField()
    token = models.CharField(max_length=255, null=True)
    expires = models.DateTimeField(null=True)
    verified = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'user'

portal/forms.py
from django import forms
#from captcha.fields import CaptchaField

from captcha.fields import ReCaptchaField
from .models import User
from django.conf import settings
import re
import os
from django.core.validators import RegexValidator

numeric = RegexValidator(r'^[0-9]+$', 'SMS verification code must contain only numbers')

class UserForm(forms.ModelForm):
    #captcha = CaptchaField(label="", error_messages=dict(invalid='Invalid CAPTCHA', required='CAPTCHA field is required'))
    captcha = ReCaptchaField(
        label="",
        error_messages=dict(required='Prove you\'re not a robot..'),
        required=True,
        attrs={
            'size': 'compact',
        })


    class Meta:
        model = User
        fields = (
            "fname",
            "lname",
            "email",
            "phone"
        )
        labels = {
            "fname": "First name",
            "lname": "Family name",
            "email": "E-mail",
            "phone": "Mobile"
        }
        # help_texts = {
        #     "fname": 'Make sure the field contains only letters (A-z) and dash (-).',
        #     "lname": 'Make sure the field contains only letters (A-z) and dash (-).',
        #     "email": 'Make sure you are not using a free webmail domain - that is not allowed.',
        #     "phone": 'Use the international formatting - starting with +'
        # }

    # check email blacklist
    def clean_email(self):
        email = self.cleaned_data.get('email')

        domain = email.split('@')[1]

        blacklist_file = os.path.join(settings.BASE_DIR, "portal/config/blacklist.txt")
        f = open(blacklist_file, 'r')

        for line in f:
            line = line.strip()
            if line.startswith('#'):
                continue
            elif re.search(domain, line, re.IGNORECASE):
                raise forms.ValidationError('Emails from domain %(invalid_domain)s are not allowed',
                                            code='invalid',
                                            params={
                                                'invalid_domain': domain
                                            }
                                            )
        return email

    def sanitize(self, name):

        name = name.strip()
        name = re.sub('[ ]{2,}', ' ', name)
        name = re.sub('\'', '', name)
        name = re.sub('[ ]*-[ ]*', '-', name)
        return name

    def clean_fname(self):
        fname = self.cleaned_data.get('fname')
        return self.sanitize(fname)

    def clean_lname(self):
        lname = self.cleaned_data.get('lname')
        return self.sanitize(lname)


# one time password (used only for form, no model)
class OtpForm(forms.Form):
    otp = forms.CharField(max_length=6, required=False, label="", validators=[numeric])
    captcha = ReCaptchaField(
        label="",
        error_messages=dict(required='Prove you\'re not a robot..'),
        required=True,
        attrs={
            'size' : 'compact',
    })

portal/views.py
import smtplib
import datetime
import pytz
import pyotp
from django.shortcuts import render
from ldap3 import Tls
from .forms import UserForm, OtpForm
from .models import User
from uuid import uuid4
from ldap3 import Server, Connection, ALL
from django.conf import settings
import ssl
import logging
import urllib3
from urllib.parse import quote

log = logging.getLogger(__name__)

# Create your views here.

#
def index(request):
    log.debug("Portal started")
    return render(request, 'portal/create.html', {
        "form": UserForm(
            initial={
                "fname": "",
                "lname": "",
                "email": "",
                "phone": ""
            }
        )
    })


# called from create()
def get_user(form):
    user = User()
    user.fname = form.cleaned_data['fname']
    user.lname = form.cleaned_data['lname']
    user.email = form.cleaned_data['email']
    user.phone = form.cleaned_data['phone']
    user.token = uuid4()

    log.debug(
        "Create: fname = " + user.fname + ", lname = " + user.lname + ", email = " + user.email + ", phone = " + str(
            user.phone))
    log.info("User create  (turn debug ON for more details)")
    return user


# /create/
def create(request):
    if request.method == 'POST':
        form = UserForm(request.POST)

        if 'reload' in request.POST:
            return render(request, 'portal/create.html', {'form': form, 'hide': True})

        if form.is_valid():
            user = get_user(form)
            user.save()
            request.session['uid'] = user.id

            log.info("User id:" + str(user.id) + ", entries are valid")
            log.info("Calling sendotp")

            return send_otp(request)
    else:
        form = UserForm()

    # not valid, retry
    log.debug("Invalid entry")
    return render(request, 'portal/create.html', {"form": form })


def send_otp(request):
    # /sendotp
    if 'uid' not in request.session:
        log.debug("uid not in request")
        return render(request, 'portal/create.html', { "form": UserForm() })

    uid = request.session['uid']
    user = User.objects.get(pk=uid)
    log.debug("got uid: " + str(uid))

    # generate secret and timestamp
    secret = pyotp.random_base32()
    created_at = datetime.datetime.now()

    # send secret to veryfyotp()
    request.session['secret'] = secret
    request.session['created_at'] = created_at.isoformat()

    # generate otp
    totp = pyotp.TOTP(secret)
    otp = totp.at(created_at)

    sms_text = 'Registration OTP: ' + str(otp)
    mobile_number = str(user.phone).replace('+','00')

    sms_status = send_sms(sms_text, mobile_number)

    if sms_status != "0" and sms_status != "3":
        # FIXME: add a error message so the user know what happened
        # use .messages(request, "Internal error, the SMS was unable to be sent")
        return render(request, 'portal/create.html', {"form": UserForm()})

    return render(request, 'portal/verifyotp.html', {'otpform': OtpForm(), 'user': user})


def verify_otp(request):
    # /verifyotp
    # get data from POST and session
    otpform = OtpForm(request.POST)

    if 'uid' not in request.session:
        log.debug("verifyotp: uid not in session")
        form = UserForm()
        return render(request, 'portal/create.html', {"form": form})

    uid = request.session['uid']
    user = User.objects.get(pk=uid)

    if not otpform.is_valid():
        return render(request, 'portal/verifyotp.html',
                      {'otpform': otpform, 'user': user})

    if 'resend' in request.POST:
        log.debug("verifyotp: Button resend pushed")
        return send_otp(request)

    else:
        secret = request.session['secret']
        created_at = datetime.datetime.strptime(request.session['created_at'], "%Y-%m-%dT%H:%M:%S.%f")

        totp = pyotp.TOTP(secret)
        if otpform.is_valid():
            otp = otpform.cleaned_data['otp']

            if totp.verify(otp, created_at):
                #if True:
                log.debug("verifyotp: User id:" + str(user.id) + ", otp match!")

                send_email_status = send_email(User.objects.get(pk=request.session['uid']))
                if send_email_status:
                    return render(request, 'portal/sendemail.html')
                else:
                    return render(request, 'portal/sendemail_error.html')
            else:
                # no match, retry
                log.debug("verifyotp: User id:" + str(user.id) + ", Invalid otp: " + otp)
                otpform.add_error("otp", "SMS OTP is invalid")

                log.debug('verifyotp: Unable to verify')

    return render(request, 'portal/verifyotp.html',
                  {'otpform': otpform, 'user': user})


# called from verifyotp()
def send_email(user):
    # set expires
    today = datetime.datetime.now()
    user.expires = today + datetime.timedelta(hours=24)
    user.save()

    url = settings.DOMAIN + "/activate/" + str(user.id) + "/" + user.token
    full_url = settings.HTTP_SCHEME + str(url).replace('//', '/')
    email_text = "From: %s\nTo: %s\nSubject: %s\n\n%s\n\n%s\n\n%s" % (settings.EMAIL_SENDER, user.email, settings.EMAIL_SUBJECT, settings.EMAIL_BODY, str(full_url), settings.EMAIL_SIGNATURE)

    try:
        log.debug(email_text)

        server = smtplib.SMTP(host=settings.EMAIL_HOST, port=settings.EMAIL_PORT, timeout=5)
        server.ehlo()
        server.sendmail(settings.EMAIL_HOST_USER, user.email, email_text)
        server.close()

        log.info("User id:" + str(user.id) + ", email sent")
        return True

    except Exception as err:
        log.error("User id:" + str(user.id) + ", unable to send email to " + user.email)
        log.debug("Exception while trying to send email: " + str(err))
        return False



def send_to_ldap(user):
# called from activate()
    try:
        # TLS
        if settings.LDAP_SSL:
            tls = Tls(ca_certs_file=settings.CA_CERTS_FILE,
                      validate=ssl.CERT_REQUIRED,
                      version=ssl.PROTOCOL_TLSv1)
            server = Server(host=settings.LDAP_HOST, port=settings.LDAP_PORT, use_ssl=True, tls=tls)
        else:
            server = Server(host=settings.LDAP_HOST, port=settings.LDAP_PORT, use_ssl=False)
        conn = Connection(server, user=settings.LDAP_USER, password=settings.LDAP_PSWD, auto_bind=True)
        conn.bind()

        # change DN !!!
        ## FIXME: THIS SHOULD BE RANDOM!
        #dn_text = "cn=" + user.fname + " " + user.lname + ", " + settings.LDAP_USERS_DN
        dn_text = "cn=" + str(user.id) + ", " + settings.LDAP_USERS_DN

        ldap_add_log = conn.add(dn_text, ['inetOrgPerson'], attributes={'givenName': user.fname, 'sn': user.lname,
                                                       'mobile': str(user.phone), 'mail': user.email})

        if ldap_add_log:
            log.debug("User id:" + str(user.id) + ", user added to DN: " + dn_text)
            return True
        else:
            log.debug("ERROR adding user id:" + str(user.id) + " to ldap. Fishy.")
            log.debug(ldap_add_log.result)

        return False

    except Exception as e:
        log.error("User id:" + str(user.id) + ", unable to connect to LDAP host: " + settings.LDAP_HOST)
        log.error(e)
        return False


# /activate/34/44eee00...
def activate(request, uid, token):
    try:
        utc = pytz.UTC
        user = User.objects.get(id=uid, token=token)
        now = utc.localize(datetime.datetime.now())
        if user.expires > now and user.verified == False:
            log.debug("User id:" + str(user.id) + " sending to ldap")
            if send_to_ldap(user):
                user.verified = True
                user.save()
                log.info("User id: " + str(user.id) + " activated")
                return render(request, 'portal/activated.html', {'user': user})
            else:
                log.error("Unable to connect to LDAP host!")
                return render(request, 'portal/activated_error.html')

            # to delete:
            # return render(request, 'portal/activated.html', {'user': user})

    except Exception as e:
        log.error(e)
        return render(request, 'portal/expired.html')

    log.debug("User id:" + str(user.id) + ", activation link expired or already active.")
    return render(request, 'portal/expired.html')


def send_sms(smsContent, phonenumber):
    try:
        http = urllib3.ProxyManager(settings.PROXY)
    except:
        log.info("Proxy setting not found while loading sending SMS, will try without it")
        http = urllib3.PoolManager()

    appUrl = settings.SMS_APP_URL
    username = settings.SMS_USER
    password = settings.SMS_PSWD

    requesturl = appUrl + '?username=' + username + '&password=' + password + '&to=' + phonenumber \
                 + '&charset=UTF-8&coding=2&text=' + quote(smsContent)
    log.debug("URL to be requested: " + str(requesturl))

    try:
        r = http.request('GET', requesturl)

        status_line = r.data.decode('utf-8')
        status_code = status_line.split(":")[0].strip()
        log.info("SendSMS: XXXX" + str(phonenumber)[-6:] + ", SMS Gateway returned: " + str(status_line))
        log.debug("SendSMS: " + str(phonenumber) + ", SMS Gateway returned: " + str(status_line))
        log.debug("HTTP request: \n" +  str(r.data.decode('utf-8')))
        return status_code

    except Exception as e:
        log.error("Error: " + str(e))


# def bulk(request):
#     # return a textarea form
#     #
#     # the form must be
#     # use built-in python csv modul
#     # create array of Users
#     # loop over lines, parse the lines, create user object

portal/templates/portal/activated.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% load staticfiles %}

{% block info_block %}
    <h2>Your registration request has been verified!</h2>
    <br>
    First name: {{ user.fname }} <br>
    Family name: {{ user.lname }} <br>
    E-mail: {{ user.email }} <br>
    Phone: {{ user.phone }} <br><br>

    <p align="center" style="font-family:monospace;"><br>
        <a href="{% url 'portal:index' %}"> <img src="{% static 'portal/check-circular-button.png' %}" width="50%"></a>
    </p>
    <h4>Sit tight, instructions are coming your way...</h4>
{% endblock %}

portal/templates/portal/activated_error.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block info_block %}
    <h1>We're unable to activate you at the moment.</h1> <br>
    <h2>Monkeys are hard at work trying to fix that.</h2><br>
    <h3>We swear.</h3>
    <h2 style="font-family:monospace;">¯\_(ツ)_/¯</h2>

{% endblock %}

portal/templates/portal/base.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pan-Net Infrastructure Registration Portal{% endblock %}</title>
    <link href="{% static 'portal/sticky-footer.css' %}" rel="stylesheet">
</head>
<body >

<div class="container-fluid">
        <div class="row" style="background: #f9f9f9;"><br></div>
        <div class="row" style="background: #f9f9f9;">
            <div class="col-xs-3 col-sm-3 col-lg-2" align="right">
                   <a href="{% url 'portal:index' %}"> <img src="{% static 'portal/telekom-logo.png' %}" width="50%"></a>
            </div>
            <div class="col-xs-6 col-sm-6 col-lg-8" align="center">
                <h2>Pan-Net Infrastructure ID Registration Portal</h2>
            </div>
            <div class="col-xs-3 col-sm-3 col-lg-2">

            </div>
        </div>

        <div class="row">
            <br><br>
            <div class="col-xs-3 col-sm-4"></div>
            <div class="col-xs-6 col-sm-4" align="center">
                {% block info_block %}{% endblock %}
            </div>
            <div class="col-xs-3 col-sm-4"></div>
        </div>

        <div class="row">
            <div class="col-xs-3 col-sm-4"></div>
            <div class="col-xs-6 col-sm-4" align="center" style="background: #f9f9f9;">
                {% block form_block %}{% endblock %}
            </div>
            <div class="col-xs-3 col-sm-4"></div>
        </div>
        <div class="row"><p></p></div>
        <div class="row"><p></p></div>
        <div class="row" align="center" >

        </div>
</div>
   <footer class="footer">
      <div class="container" align="center">
        <span class="text-muted"><strong>Problems registering?</strong> Contact <a href="mailto:pan-net.soc@telekom.com">Pan-Net SOC</a></span>
      </div>
    </footer>

portal/templates/portal/create.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block form_block %}
    <form action="{% url 'portal:create' %}" method="post" class="form">
                    {% csrf_token %}
                    {% bootstrap_form_errors form type='all' %}
                    {% bootstrap_field form.fname placeholder='Alice' size='lg' align='center' %}
                    {% bootstrap_field form.lname placeholder='Von Wonderland' size='lg' %}
                    {% bootstrap_field form.email placeholder='a.wonderland@acme.com' size='lg' %}
                    {% bootstrap_field form.phone placeholder='+421000000000' size='lg' %}
                    {% bootstrap_field form.captcha  %}

                    {% buttons %}
                        <button type="submit" name="submit" class="btn btn-primary">
                            {% bootstrap_icon "pencil" %} Register
                        </button>
                    {% endbuttons %}
                </form>
{% endblock %}

portal/templates/portal/expired.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block info_block %}
    <h1>An internal error occurred</h1>
    <h2 style="font-family:monospace;">¯\_(ツ)_/¯</h2>
    <br>
        <h4><u>Possible causes</u></h4>
    <ul>
        user is already verified (not you? contact <a href="mailto:pan-net.soc@telekom.com">Pan-Net SOC</a>)<br>
        the verification link has already expired (24h) (register again)<br>
        verification link is incorrect (you hax0r)<br>
    </ul>
{% endblock %}

portal/templates/portal/receive.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block info_block %}
    <h2>Sit tight</h2>
    <p>Bits and bytes are flying around, you should get an email soon.</p>
    <p>Here is the registration request summary:</p>
    First name: {{ fname }} <br>
    Family name: {{ lname }} <br>
    E-mail: {{ email }} <br>
    phone: {{ phone }} <br>
{% endblock %}

portal/templates/portal/sendemail.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block info_block %}
    <h2>You're almost there...</h2>
    <br><br>
    <h4>A verification link was sent to your email address</h4>
    <h3>You can close this window now.</h3>
{% endblock %}

portal/templates/portal/sendemail_error.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block info_block %}
    <h1>We're unable to send you a verification email at the moment.</h1><br>
    <h2>Monkeys are hard at work trying to fix that.</h2><br>
    <h3>We swear.</h3>
    <h2 style="font-family:monospace;">¯\_(ツ)_/¯</h2>
{% endblock %}

portal/templates/portal/sendotp.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block info_block %}

{% endblock %}

{% block form_block %}
     <br>
     <form action="{% url 'portal:sendotp' %}" method="post" class="form">
         {% csrf_token %}
         {% bootstrap_form_errors sendotpcaptchaform type='all' %}
         {% bootstrap_field sendotpcaptchaform.captcha %}

         {% buttons %}
             <button type="button" onclick="window.history.back();" class="btn btn-warning">
                 {% bootstrap_icon "pencil" %} Edit
             </button>
             <button type="submit" value="Send SMS" class="btn btn-primary">
                 {% bootstrap_icon "send" %} Yes, It Does
             </button>
        {% endbuttons %}
         <input type="hidden" name="uid" value="{{ user.id }}">
    </form>
    <br>
{% endblock %}

portal/templates/portal/verifyotp.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block info_block %}

    <h3>Does this make sense to you?</h3><br>
    <strong>{{ user.fname }} <br>
    <strong>{{ user.lname }} <br>
    <strong>{{ user.email }} <br>
    <strong>{{ user.phone }}</strong><br>

     <h3>Verify {{ user.phone }}</h3>
{% endblock %}
{% block form_block %}
     <form action="{% url 'portal:verifyotp' %}" method="post" autocomplete="off" class="form">
         {% csrf_token %}
         <br>
         {% bootstrap_form_errors otpform type='all' %}
         {% bootstrap_field otpform.otp placeholder="Enter the code from the SMS.." size='lg' align='center' %}
         {% bootstrap_field otpform.captcha align='center' %}

         <input type="hidden" name="uid" value="{{ user.id }}">

         {% buttons %}
         <button type="submit" name="resend" class="btn">
             {% bootstrap_icon "refresh" %} Resend SMS
         </button>
         <button type="submit" value="Confirm" class="btn btn-primary">
             {% bootstrap_icon "send" %} Confirm
         </button>
        {% endbuttons %}
    </form>
{% endblock %}